name: mediainteraktiffotografi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  smooth_page_indicator: ^1.0.0+2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/home/
  - assets/icon/
  - assets/image/
  - assets/image/dasarfotografi/
  - assets/image/bidangpandang/
  - assets/image/sudutpandang/
  - assets/image/metering/
  - assets/image/pencahayaan/

